import {
  User, Party, Transaction, Transfer,
  StaffHolding, Notification, FeedItem
} from './types';

// ─── USERS ───────────────────────────────────────────────────────────────────

export const currentUser: User = {
  id: 'u1',
  name: 'Accountant',
  phone: '+91 98765 00001',
  role: 'admin',
  active: true,
};

export const users: User[] = [
  { id: 'u1', name: 'Accountant',  phone: '+91 98765 00001', role: 'admin',     active: true },
  { id: 'u2', name: 'Owner 1',     phone: '+91 98765 00002', role: 'admin',     active: true },
  { id: 'u3', name: 'Owner 2',     phone: '+91 98765 00003', role: 'admin',     active: true },
  { id: 'u4', name: 'CA',          phone: '+91 98765 00004', role: 'admin',     active: true },
  { id: 'u5', name: 'Suresh',      phone: '+91 98765 00005', role: 'collector', active: true },
  { id: 'u6', name: 'Raju',        phone: '+91 98765 00006', role: 'collector', active: true },
  { id: 'u7', name: 'Khaleel',     phone: '+91 98765 00007', role: 'collector', active: true },
  { id: 'u8', name: 'Vijay',       phone: '+91 98765 00008', role: 'collector', active: true },
  { id: 'u9', name: 'Farhan',      phone: '+91 98765 00009', role: 'collector', active: true },
  { id: 'u10', name: 'Imran',      phone: '+91 98765 00010', role: 'collector', active: true },
];

export const collectors = users.filter(u => u.role === 'collector');
export const admins = users.filter(u => u.role === 'admin');

// ─── PARTIES ─────────────────────────────────────────────────────────────────

export const parties: Party[] = [
  {
    id: 'p1',
    name: 'Ramesh Constructions',
    contactPerson: 'Ramesh Kumar',
    phone: '+91 98001 11111',
    balance: 240000,
    deadlineDays: 7,
    type: 'long_term',
    status: 'active',
    createdBy: 'u1',
    notes: 'Regular client since 2021. Usually pays on time.',
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: 'p2',
    name: 'Kapoor Builders',
    contactPerson: 'Rajiv Kapoor',
    phone: '+91 98001 22222',
    balance: 115000,
    deadlineDays: 7,
    type: 'long_term',
    status: 'active',
    createdBy: 'u1',
    createdAt: '2024-02-01T09:00:00Z',
  },
  {
    id: 'p3',
    name: 'Singh & Sons',
    contactPerson: 'Harpreet Singh',
    phone: '+91 98001 33333',
    balance: 70000,
    deadlineDays: 5,
    type: 'long_term',
    status: 'active',
    createdBy: 'u1',
    createdAt: '2024-02-15T09:00:00Z',
  },
  {
    id: 'p4',
    name: 'Mehta Infra',
    contactPerson: 'Sunil Mehta',
    phone: '+91 98001 44444',
    balance: 0,
    deadlineDays: 7,
    type: 'long_term',
    status: 'active',
    createdBy: 'u1',
    createdAt: '2024-01-20T09:00:00Z',
  },
  {
    id: 'p5',
    name: 'Gupta Cement Co.',
    contactPerson: 'Anand Gupta',
    phone: '+91 98001 55555',
    balance: 380000,
    deadlineDays: 10,
    type: 'long_term',
    status: 'active',
    createdBy: 'u1',
    createdAt: '2024-03-01T09:00:00Z',
  },
  {
    id: 'p6',
    name: 'Reddy Constructions',
    contactPerson: 'Venkat Reddy',
    phone: '+91 98001 66666',
    balance: 95000,
    deadlineDays: 7,
    type: 'long_term',
    status: 'active',
    createdBy: 'u1',
    createdAt: '2024-03-10T09:00:00Z',
  },
  {
    id: 'p7',
    name: 'Sharma & Co.',
    contactPerson: 'Deepak Sharma',
    phone: '+91 98001 77777',
    balance: 0,
    deadlineDays: 7,
    type: 'one_time',
    status: 'inactive',
    createdBy: 'u1',
    createdAt: '2024-02-05T09:00:00Z',
  },
  {
    id: 'p8',
    name: 'Agarwal Infra',
    contactPerson: 'Rohit Agarwal',
    phone: '+91 98001 88888',
    balance: 175000,
    deadlineDays: 7,
    type: 'long_term',
    status: 'active',
    createdBy: 'u4',
    createdAt: '2024-03-15T09:00:00Z',
  },
  {
    id: 'p9',
    name: 'Patel Builders',
    contactPerson: 'Nitin Patel',
    phone: '+91 98001 99999',
    balance: 60000,
    deadlineDays: 5,
    type: 'one_time',
    status: 'active',
    createdBy: 'u1',
    createdAt: '2024-03-20T09:00:00Z',
  },
  {
    id: 'p10',
    name: 'Khan Projects',
    contactPerson: 'Arshad Khan',
    phone: '+91 98001 10101',
    balance: 310000,
    deadlineDays: 10,
    type: 'long_term',
    status: 'active',
    createdBy: 'u4',
    createdAt: '2024-01-25T09:00:00Z',
  },
];

// ─── TRANSACTIONS ─────────────────────────────────────────────────────────────

export const transactions: Transaction[] = [
  {
    id: 't1',
    partyId: 'p2',
    partyName: 'Kapoor Builders',
    type: 'credit',
    amount: 200000,
    doneBy: 'u1',
    doneByName: 'Accountant',
    note: 'New supply delivered Mar 20',
    createdAt: '2024-03-20T09:00:00Z',
  },
  {
    id: 't2',
    partyId: 'p2',
    partyName: 'Kapoor Builders',
    type: 'debit',
    amount: 85000,
    paymentMethod: 'cash',
    receivedBy: 'u5',
    receivedByName: 'Suresh',
    deadlineDate: '2024-03-29T00:00:00Z',
    doneBy: 'u5',
    doneByName: 'Suresh',
    createdAt: '2024-03-22T11:30:00Z',
  },
  {
    id: 't3',
    partyId: 'p2',
    partyName: 'Kapoor Builders',
    type: 'debit',
    amount: 85000,
    paymentMethod: 'cash',
    receivedBy: 'u5',
    receivedByName: 'Suresh',
    deadlineDate: '2024-03-31T00:00:00Z',
    doneBy: 'u5',
    doneByName: 'Suresh',
    createdAt: '2024-03-24T10:05:00Z',
  },
  {
    id: 't4',
    partyId: 'p3',
    partyName: 'Singh & Sons',
    type: 'debit',
    amount: 140000,
    paymentMethod: 'cash',
    receivedBy: 'u6',
    receivedByName: 'Raju',
    deadlineDate: '2024-03-27T00:00:00Z',
    doneBy: 'u6',
    doneByName: 'Raju',
    createdAt: '2024-03-22T09:30:00Z',
  },
  {
    id: 't5',
    partyId: 'p4',
    partyName: 'Mehta Infra',
    type: 'debit',
    amount: 210000,
    paymentMethod: 'online',
    receivedBy: 'u1',
    receivedByName: 'Accountant',
    doneBy: 'u1',
    doneByName: 'Accountant',
    createdAt: '2024-03-23T14:15:00Z',
  },
  {
    id: 't6',
    partyId: 'p1',
    partyName: 'Ramesh Constructions',
    type: 'credit',
    amount: 400000,
    doneBy: 'u1',
    doneByName: 'Accountant',
    note: 'New supply Mar 12',
    createdAt: '2024-03-12T09:00:00Z',
  },
  {
    id: 't7',
    partyId: 'p1',
    partyName: 'Ramesh Constructions',
    type: 'debit',
    amount: 160000,
    paymentMethod: 'cash',
    receivedBy: 'u8',
    receivedByName: 'Vijay',
    deadlineDate: '2024-03-19T00:00:00Z',
    doneBy: 'u8',
    doneByName: 'Vijay',
    createdAt: '2024-03-12T15:00:00Z',
  },
];

// ─── TRANSFERS ────────────────────────────────────────────────────────────────

export const transfers: Transfer[] = [
  {
    id: 'tr1',
    fromUserId: 'u6',
    fromUserName: 'Raju',
    toUserId: 'u7',
    toUserName: 'Khaleel',
    amount: 140000,
    partyId: 'p3',
    partyName: 'Singh & Sons',
    transactionId: 't4',
    createdAt: '2024-03-23T11:00:00Z',
  },
  {
    id: 'tr2',
    fromUserId: 'u7',
    fromUserName: 'Khaleel',
    toUserId: 'u1',
    toUserName: 'Accountant',
    amount: 210000,
    partyId: 'p4',
    partyName: 'Mehta Infra',
    transactionId: 't5',
    createdAt: '2024-03-23T16:00:00Z',
  },
];

// ─── STAFF HOLDINGS ───────────────────────────────────────────────────────────

export const staffHoldings: StaffHolding[] = [
  {
    userId: 'u5',
    name: 'Suresh',
    role: 'collector',
    totalHolding: 225000,
    holdings: [
      { partyId: 'p2', partyName: 'Kapoor Builders', amount: 85000,  since: '2024-03-24T10:05:00Z', daysHeld: 2, isOverdue: false },
      { partyId: 'p2', partyName: 'Kapoor Builders', amount: 85000,  since: '2024-03-22T11:30:00Z', daysHeld: 4, isOverdue: false },
      { partyId: 'p9', partyName: 'Patel Builders',  amount: 55000,  since: '2024-03-23T09:00:00Z', daysHeld: 3, isOverdue: false },
    ],
  },
  {
    userId: 'u7',
    name: 'Khaleel',
    role: 'collector',
    totalHolding: 140000,
    holdings: [
      { partyId: 'p3', partyName: 'Singh & Sons', amount: 140000, since: '2024-03-23T11:00:00Z', daysHeld: 4, isOverdue: true },
    ],
  },
  {
    userId: 'u6',
    name: 'Raju',
    role: 'collector',
    totalHolding: 380000,
    holdings: [
      { partyId: 'p5', partyName: 'Gupta Cement Co.', amount: 380000, since: '2024-03-21T10:00:00Z', daysHeld: 5, isOverdue: false },
    ],
  },
  {
    userId: 'u8',
    name: 'Vijay',
    role: 'collector',
    totalHolding: 85000,
    holdings: [
      { partyId: 'p1', partyName: 'Ramesh Constructions', amount: 85000, since: '2024-03-22T15:00:00Z', daysHeld: 4, isOverdue: false },
    ],
  },
  {
    userId: 'u9',
    name: 'Farhan',
    role: 'collector',
    totalHolding: 0,
    holdings: [],
  },
  {
    userId: 'u10',
    name: 'Imran',
    role: 'collector',
    totalHolding: 0,
    holdings: [],
  },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────

export const notifications: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    type: 'collection',
    message: 'Suresh collected Rs. 85,000 cash from Kapoor Builders',
    partyId: 'p2',
    partyName: 'Kapoor Builders',
    read: false,
    createdAt: '2024-03-24T10:05:00Z',
  },
  {
    id: 'n2',
    userId: 'u1',
    type: 'handover',
    message: 'Raju passed Rs. 1,40,000 to Khaleel — originally from Singh & Sons',
    partyId: 'p3',
    partyName: 'Singh & Sons',
    read: false,
    createdAt: '2024-03-23T11:00:00Z',
  },
  {
    id: 'n3',
    userId: 'u1',
    type: 'settled',
    message: 'Accountant received Rs. 2,10,000 from Khaleel — Mehta Infra settled',
    partyId: 'p4',
    partyName: 'Mehta Infra',
    read: false,
    createdAt: '2024-03-23T16:00:00Z',
  },
  {
    id: 'n4',
    userId: 'u1',
    type: 'collection',
    message: 'Vijay collected Rs. 85,000 from Ramesh Constructions',
    partyId: 'p1',
    partyName: 'Ramesh Constructions',
    read: true,
    createdAt: '2024-03-22T15:00:00Z',
  },
  {
    id: 'n5',
    userId: 'u1',
    type: 'overdue',
    message: 'Khaleel has held Rs. 1,40,000 from Singh & Sons for 4 days. Deadline was 3 days.',
    partyId: 'p3',
    partyName: 'Singh & Sons',
    read: false,
    createdAt: '2024-03-23T08:00:00Z',
  },
  {
    id: 'n6',
    userId: 'u1',
    type: 'overdue',
    message: 'Ramesh Constructions — Rs. 2,40,000 outstanding for 12 days. Deadline was 7 days.',
    partyId: 'p1',
    partyName: 'Ramesh Constructions',
    read: false,
    createdAt: '2024-03-20T08:00:00Z',
  },
  {
    id: 'n7',
    userId: 'u1',
    type: 'overdue',
    message: 'Raju has held Rs. 3,80,000 from Gupta Cement for 5 days. Deadline in 5 days.',
    partyId: 'p5',
    partyName: 'Gupta Cement Co.',
    read: true,
    createdAt: '2024-03-21T08:00:00Z',
  },
];

// ─── LIVE FEED ────────────────────────────────────────────────────────────────

export const feedItems: FeedItem[] = [
  {
    id: 'f1',
    type: 'collection',
    description: 'Suresh collected from Kapoor Builders',
    amount: 85000,
    partyName: 'Kapoor Builders',
    personName: 'Suresh',
    paymentMethod: 'cash',
    createdAt: '2024-03-24T10:05:00Z',
  },
  {
    id: 'f2',
    type: 'handover',
    description: 'Raju handed to Khaleel',
    amount: 140000,
    partyName: 'Singh & Sons',
    personName: 'Raju',
    createdAt: '2024-03-23T11:00:00Z',
  },
  {
    id: 'f3',
    type: 'settled',
    description: 'Accountant received from Khaleel',
    amount: 210000,
    partyName: 'Mehta Infra',
    personName: 'Accountant',
    paymentMethod: 'online',
    createdAt: '2024-03-23T16:00:00Z',
  },
  {
    id: 'f4',
    type: 'collection',
    description: 'Vijay collected from Ramesh Constructions',
    amount: 85000,
    partyName: 'Ramesh Constructions',
    personName: 'Vijay',
    paymentMethod: 'cash',
    createdAt: '2024-03-22T15:00:00Z',
  },
  {
    id: 'f5',
    type: 'collection',
    description: 'Raju collected from Gupta Cement Co.',
    amount: 380000,
    partyName: 'Gupta Cement Co.',
    personName: 'Raju',
    paymentMethod: 'cash',
    createdAt: '2024-03-21T10:00:00Z',
  },
];

// ─── DASHBOARD STATS ──────────────────────────────────────────────────────────

export const dashboardStats = {
  totalOutstanding: parties
    .filter(p => p.status === 'active')
    .reduce((sum, p) => sum + p.balance, 0),
  cashInCirculation: staffHoldings
    .reduce((sum, s) => sum + s.totalHolding, 0),
  collectedToday: 85000,
  overdueCount: 3,
};